# Generated by Django 4.2 on 2023-05-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('queue_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('status', models.CharField(blank=True, choices=[('Кезектер тізімінде', 'New'), ('Қызмет көрсетілуде', 'Processinprogress'), ('Қызмет аяқталды', 'End')], default='Кезектер тізімінде', max_length=20)),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('queue_type', models.CharField(blank=True, choices=[('Грант', 'Grant'), ('Ақылы', 'Budget'), ('Басқа', 'Other')], default='Басқа', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Queue',
                'verbose_name_plural': 'Queues',
                'ordering': ('created_at',),
            },
        ),
    ]
